# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        hwi_oauth.user.provider:
            id: hwi_oauth.user.provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path:   /logout
            oauth:
                resource_owners:
                    github:          "/login/check-github"
                login_path:        connect_github
                use_forward:       false
                failure_path:      connect_github

                oauth_user_provider:
                    service: hwi_oauth.user.provider

    access_control:
        - { path: ^(.*)/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }